# 使用官方的 Node.js 24 镜像作为基础镜像
FROM node:24

# 设置工作目录
WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com/
# # 复制 package.json 和 package-lock.json 文件到工作目录
# COPY package*.json ./

# # 安装依赖
# RUN npm install

# # 将本地代码挂载到容器中
# VOLUME ["/app"]

# # 暴露端口
# EXPOSE 8080

# # 启动 Vue.js 开发服务器
# CMD ["npm", "run", "serve"]