# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Builds ultralytics/ultralytics:latest image on DockerHub https://hub.docker.com/r/ultralytics/ultralytics
# Image is CUDA-optimized for YOLO single/multi-GPU training and inference

# Start FROM PyTorch image https://hub.docker.com/r/pytorch/pytorch or nvcr.io/nvidia/pytorch:25.02-py3
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/pytorch/pytorch:2.8.0-cuda12.8-cudnn9-runtime

# Set environment variables
# Avoid DDP error "MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library"
# Suppress TensorFlow cuDNN, cuBLAS, and cuFFT Registration Warnings
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_BREAK_SYSTEM_PACKAGES=1 \
    MKL_THREADING_LAYER=GNU \
    OMP_NUM_THREADS=1 \
    TF_CPP_MIN_LOG_LEVEL=3



WORKDIR /ultralytics

RUN pip install  ultralytics -i  https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install fastapi -i  https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install python-multipart -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install uvicorn -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --upgrade   "onnx>=1.12.0,<=1.19.1"   onnxruntime   onnxslim>=0.1.71 -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libx11-6 \
    && rm -rf /var/lib/apt/lists/*