FROM docker.1ms.run/library/python:3.11-slim

WORKDIR /labelu

RUN pip3 install labelu -i https://pypi.tuna.tsinghua.edu.cn/simple

ENV MEDIA_HOST http://localhost:8000

EXPOSE 8000

CMD ["sh", "-c", "labelu --host=0.0.0.0 --media-host=$MEDIA_HOST"]